# Generated by Django 5.0.6 on 2025-08-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_acc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='addres',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
